apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID:      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName:      #enter keyvault name
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName:   #name of secrets
          objectType: secret        # object types: secret, key, or cert     
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    
    tenantId: "097b85e8-2f0c-4726-a9d5-af15f7621ce5"
          # The tenant ID of the key vault
  secretObjects:
    - data:
      - key:                    # data field to populate
        objectName:                  # name of the mounted content to sync; this could be the object name or the object alias
      secretName:                  # name of the Kubernetes secret object
      type: Opaque  
      
